"""empty message

Revision ID: 3b6482583561
Revises: 8282a15d53b
Create Date: 2018-04-20 23:36:33.768000

"""

# revision identifiers, used by Alembic.
revision = '3b6482583561'
down_revision = '8282a15d53b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
