"""empty message

Revision ID: 473ce330ac9b
Revises: 3b6482583561
Create Date: 2018-04-21 00:12:16.796000

"""

# revision identifiers, used by Alembic.
revision = '473ce330ac9b'
down_revision = '3b6482583561'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_book_created'), 'book', ['created'], unique=False)
    op.add_column('book_comment', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_book_comment_created'), 'book_comment', ['created'], unique=False)
    op.add_column('house', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_house_created'), 'house', ['created'], unique=False)
    op.add_column('house_comment', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_house_comment_created'), 'house_comment', ['created'], unique=False)
    op.add_column('phone', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_phone_created'), 'phone', ['created'], unique=False)
    op.add_column('phone_comment', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_phone_comment_created'), 'phone_comment', ['created'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_comment_created'), table_name='phone_comment')
    op.drop_column('phone_comment', 'created')
    op.drop_index(op.f('ix_phone_created'), table_name='phone')
    op.drop_column('phone', 'created')
    op.drop_index(op.f('ix_house_comment_created'), table_name='house_comment')
    op.drop_column('house_comment', 'created')
    op.drop_index(op.f('ix_house_created'), table_name='house')
    op.drop_column('house', 'created')
    op.drop_index(op.f('ix_book_comment_created'), table_name='book_comment')
    op.drop_column('book_comment', 'created')
    op.drop_index(op.f('ix_book_created'), table_name='book')
    op.drop_column('book', 'created')
    ### end Alembic commands ###
