"""empty message

Revision ID: 8282a15d53b
Revises: None
Create Date: 2018-04-20 23:30:24.008000

"""

# revision identifiers, used by Alembic.
revision = '8282a15d53b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=11), nullable=True),
    sa.Column('roles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.String(length=20), nullable=True),
    sa.Column('date_time', sa.String(length=20), nullable=True),
    sa.Column('payable', sa.String(length=20), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('place', sa.String(length=20), nullable=True),
    sa.Column('date_time', sa.String(length=20), nullable=True),
    sa.Column('community', sa.String(length=20), nullable=True),
    sa.Column('payable', sa.String(length=20), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.String(length=20), nullable=True),
    sa.Column('date_time', sa.String(length=20), nullable=True),
    sa.Column('payable', sa.String(length=20), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=20), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=20), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=20), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=20), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=20), nullable=True),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone_id'], ['phone.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=20), nullable=True),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone_id'], ['phone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_photo')
    op.drop_table('phone_comment')
    op.drop_table('house_photo')
    op.drop_table('house_comment')
    op.drop_table('book_photo')
    op.drop_table('book_comment')
    op.drop_table('phone')
    op.drop_table('house')
    op.drop_table('book')
    op.drop_table('user')
    ### end Alembic commands ###
